[project]
name = "dbca-utils"
version = "3.0.13"
description = "Utilities for DBCA Django apps"
authors = [
  { name = "Rocky Chen", email = "rocky.chen@dbca.wa.gov.au" },
  { name = "Ashley Felton", email = "ashley.felton@dbca.wa.gov.au" },
]
readme = "README.md"
license = "Apache-2.0"
classifiers = [
  "Framework :: Django",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6.0",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.12,<4.0"
dependencies = [
  "django>=5.2,<6.2",
  "markupsafe>=3.0",
  "psutil>=7.2",
  "requests>=2.33",
]

[project.urls]
Homepage = "https://github.com/dbca-wa/dbca-utils"
Repository = "https://github.com/dbca-wa/dbca-utils.git"
Changelog = "https://github.com/dbca-wa/dbca-utils/blob/main/CHANGELOG.md"
GitHub = "https://github.com/dbca-wa/dbca-utils"

[dependency-groups]
dev = [
  "pytest-django>=4.12.0",
  "pytest-sugar>=1.1.1",
  "tox>=4.53.0",
  "tox-uv>=1.35.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.uv]
package = true

[tool.pytest.ini_options]
# https://pytest-django.readthedocs.io/en/latest/configuring_django.html#pyproject-toml-settings
DJANGO_SETTINGS_MODULE = "tests.settings"
# https://pytest-django.readthedocs.io/en/latest/managing_python_path.html#using-pytest-s-pythonpath-option
pythonpath = ". src"
# https://pytest-django.readthedocs.io/en/latest/faq.html#my-tests-are-not-being-found-why
python_files = "tests.py test_*.py"

[tool.ruff]
line-length = 140
indent-width = 4

[tool.ruff.lint]
ignore = ["E265", "E501", "E722"]
